name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Django Test
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        run: |
          sudo -u postgres createuser postgres
          createdb -h localhost -p 5432 -U postgres postgres
          pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
          python manage.py test

        # continue-on-error: true
